	cmake_minimum_required(VERSION 2.6)
	add_executable(	break1 src\app\break1.c	)
	add_executable(	do-while-diff-combination src\app\do-while-diff-combination.c	)
	add_executable(	do-while-nested src\app\do-while-nested.c	)
	add_executable(	for-loop1 src\app\for-loop1.c	)
	add_executable(	nested_if src\app\nested_if.c	)
	add_executable(	break1 src\db\break1.c	)
	add_executable(	do-while-diff-combination src\db\do-while-diff-combination.c	)
	add_executable(	do-while-nested src\db\do-while-nested.c	)
	add_executable(	do-while src\db\do-while.c	)
	add_executable(	ex_4-12 src\db\ex_4-12.c	)
	add_executable(	array src\driver\array.c	)
	add_executable(	auto src\driver\auto.c	)
	add_executable(	char src\driver\char.c	)
	add_executable(	const src\driver\const.c	)
	add_executable(	double_float src\driver\double_float.c	)
	add_executable(	enum src\driver\enum.c )
	add_executable(	extern src\driver\extern.c )
	add_executable( header header\cmaster.h)

