	cmake_minimum_required(VERSION 2.6)
	add_executable(	break1 src/app/break1.c	)
	add_executable(	for-loop-infinite src/app/for-loop-infinite.c	)
	add_executable(	for-loop-nested src/app/for-loop-nested.c	)
	add_executable(	macro-elif src/db/macro-elif.c	)
	add_executable(	macro-ifdef-2 src/db/macro-ifdef-2.c	)
	add_executable(	macro-ifndef.c src/db/macro-ifndef.c	)
	add_executable(	macro-undef.c src/db/macro-undef.c	)
	add_executable(	macros-else.c src/db/macros-else.c	)
	add_executable(	auto src/driver/auto.c	)
	add_executable(	const src/driver/const.c	)
	add_executable(	double_float src/driver/double_float.c	)
	add_executable(	extern src/driver/extern.c )
